# Generated by Django 4.1.3 on 2022-11-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag_view',
        ),
    ]
