# Generated by Django 4.1.3 on 2022-12-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='image',
        ),
    ]
