# Generated by Django 4.1.3 on 2023-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Desxription'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keyword'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Desxription'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
    ]
